### ISSUE TITLE
autolab_core not installed as a catkin package!?

### ISSUE THREAD

**Issue by EAZYE9000** [BerkeleyAutomation/autolab_core#1]
HELLO

Im desperately trying to run your code since this stuff is amazing!

But I keep getting the same error lads:

WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:primesense_sensor.py not installed as catkin package. ROS functionality not available.
INFO:root:Beginning Visualization
INFO:root:Setting up for visualization.
INFO:root:Reading filenames
Traceback (most recent call last):
  File "visualize_predictions.py", line 18, in <module>
    visualizer = GQCNNPredictionVisualizer(visualization_config)
  File "build/bdist.linux-x86_64/egg/gqcnn/gqcnn_prediction_visualizer.py", line 35, in __init__
  File "build/bdist.linux-x86_64/egg/gqcnn/gqcnn_prediction_visualizer.py", line 177, in _setup
  File "build/bdist.linux-x86_64/egg/gqcnn/gqcnn_prediction_visualizer.py", line 193, in _setup_data_filenames
OSError: [Errno 2] No such file or directory: '/home/autolab/Public/data/dex-net/data/grasp_quality_regression/3dnet_kit_04_09_17_minimal'
INFO:rospy.core:signal_shutdown [atexit]

Is it okay to run the visualize_predictions.py from the tools folder? I tried installing the catkin package like this
mkdir catkin_ws
cd catkin_ws
mkdir src
catkin_make install
cd src
git clone https://github.com/BerkeleyAutomation/autolab_core.git
cd ..
catkin_make

!?

**Comment by Binaryhalibut** [comment]
autolab_core not installed as catkin package just means the RigidTransform ros methods don't work. These aren't used, so it won't affect visualize_predictions.py

The error is that your dataset_dir isn't set correctly in the gqcnn_prediction_visualizer.yaml config file. Open up that file and change dataset_dir (currently says "/home/autolab/Public/data/dex-net/data/grasp_quality_regression/3dnet_kit_04_09_17_minimal") to point to a dataset (you can download datasets from the "datasets" link in https://berkeleyautomation.github.io/gqcnn).

Similarly, also change model_dir to point to a downloaded model.

**Comment by SimonNgj** [comment]
```
Hello, I am using Jade ROS to install autolab_core by following your guide. It works fine until I do the testing, it shown that I failed to import ROS ...
arlab1@arlab1:~/catkin_ws$ cd src/autolab_core/
arlab1@arlab1:~/catkin_ws/src/autolab_core$ python setup.py test
running test
running egg_info
creating autolab_core.egg-info
writing requirements to autolab_core.egg-info/requires.txt
writing autolab_core.egg-info/PKG-INFO
writing top-level names to autolab_core.egg-info/top_level.txt
writing dependency_links to autolab_core.egg-info/dependency_links.txt
writing manifest file 'autolab_core.egg-info/SOURCES.txt'
reading manifest file 'autolab_core.egg-info/SOURCES.txt'
writing manifest file 'autolab_core.egg-info/SOURCES.txt'
running build_ext
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
test_inits (test.points_test.PointsTest) ... ok
test_bad_inits (test.rigid_transform_test.RigidTransformTest) ... ok
test_bad_transformation (test.rigid_transform_test.RigidTransformTest) ... ok
test_composition (test.rigid_transform_test.RigidTransformTest) ... ok
test_init (test.rigid_transform_test.RigidTransformTest) ... ok
test_inverse (test.rigid_transform_test.RigidTransformTest) ... ok
test_point_cloud_transformation (test.rigid_transform_test.RigidTransformTest) ... ok
test_point_transformation (test.rigid_transform_test.RigidTransformTest) ... ok
test_similarity_transformation (test.rigid_transform_test.RigidTransformTest) ... ok
```

**Comment by Binaryhalibut** [comment]
Looks like rospy or rosservice isn't being imported. Open up python and try importing rospy, then try importing rosservice. One of those should fail. If not something really weird's going on.

The ros stuff in autolab_core is totally optional by the way, and none of the GQCNN or dex-net stuff uses it.
