### ISSUE TITLE
autolab_core requires matplotlib<=2.2.0

### ISSUE THREAD

**Issue by shiy9** [BerkeleyAutomation/autolab_core#34]
**System information**

OS: Windows 10
Python version: 3.8
Installed using pip or ROS: pip

I am running into issues installing this package via pip (`pip install autolab-core`) with the following message:

Collecting matplotlib<=2.2.0
  Using cached matplotlib-2.2.0.tar.gz (37.2 MB)
ERROR: Command errored out with exit status 1:
     command: 'c:\users\shi yx\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Shi YX\\AppData\\Local\\Temp\\pip-install-adu7xe6b\\matplotlib_2f5b8f04523d4d0fa8e927fb19d04bde\\setup.py'"'"'; __file__='"'"'C:\\Users\\Shi YX\\AppData\\Local\\Temp\\pip-install-adu7xe6b\\matplotlib_2f5b8f04523d4d0fa8e927fb19d04bde\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Shi YX\AppData\Local\Temp\pip-pip-egg-info-4rubyry4'
         cwd: C:\Users\Shi YX\AppData\Local\Temp\pip-install-adu7xe6b\matplotlib_2f5b8f04523d4d0fa8e927fb19d04bde\
    Complete output (61 lines):
    ============================================================================
    Edit setup.cfg to change the build options

I am using matplotlib 3.3.4 and cannot seem to install 2.2.0. I saw a similar issue with the gqcnn package but did not find a helpful solution (I simply read about the issue but did not use the package myself).

**Comment by mjd3** [comment]
This was fixed by #33; you shouldn't have any problems if you update to version 1.0.0 or later. Let us know if you run into any other issues!
