### ISSUE TITLE
Bug in RigidTransform.linear_trajectory_to method

### ISSUE THREAD

**Issue by shivamvats** [BerkeleyAutomation/autolab_core#40]
According to the doc of ``RigidTransform.linear_trajectory_to`` method, it is supposed to return a trajectory of length `traj_len`. It doesn't do so and is not even consistent about the length of the returned trajectory wrt `traj_len`.
```
>>> from autolab_core import RigidTransform
>>> a = RigidTransform()
>>> for i in range(10):
...     print(i, len(a.linear_trajectory_to(a, i)))
...
0 2
1 3
2 4
3 5
4 6
5 8
6 9
7 9
8 10
9 12
```

**Comment by mjd3** [comment]
Fixed by #41/#42. Thanks for the PR!
