### ISSUE TITLE
TensorDataset Fails Ungracefully when config.json Does Not Exist

### ISSUE THREAD

**Issue by jeffmahler** [BerkeleyAutomation/autolab_core#7]
Users should be informed when the dataset is corrupt. This can be handled [here](https://github.com/BerkeleyAutomation/autolab_core/blob/b053a93386f83e0d55a9a7de96423311efb36740/autolab_core/tensor_dataset.py#L708).

**Comment by mjd3** [comment]
Fixed by #38.
